### ISSUE TITLE
importing ed2k links into the Android app

### ISSUE THREAD

**Issue by eadmaster** [a-pavlov/qDonkey#2]
is it possible currently to import a set of e2dk links into the app?
Is there a builtin web server like in AMLDonkey?

**Comment by a-pavlov** [comment]
Importing ed2k links is available in this application https://github.com/a-pavlov/jed2k by inserting link into text edit on transfers page. Also in the next release will be availble importing servers links and open application on ed2k link click in browser. Builtin web server are not planning because this application has Android implementation.
